server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost/spring-boot-security-demo?useSSL=false&characterEncoding=utf8
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false
  mvc:
    static-path-pattern: /static/**
    favicon:
      enabled: false